### ISSUE TITLE
Add possibility to add links, resources etc.

### ISSUE THREAD

**Issue by abeggchr** [Zuehlke/fifty-shades#18]
> Etwas was ich mir z.B. am Ende jedes Artikels wünschen würde: weiterführende Links, wo ich weitere Informationen / Beispiele / Resourcen zum Thema finde.

**Comment by abeggchr** [comment]
Vorschlag: Neben dem "article.md" file gibt es noch ein zweites "article.resources.md" file welches ebensolche Resourcen enthält.

Warum nicht einfach am Schluss des Artikels? Wird die Artikelsammlung sowohl gedruckt als auch digital (web, ebook) publiziert, dann nützen Links in einer gedruckten Ausgabe herzlich wenig. Ich würde da dann einen QR Code abbilden welcher auf auf das "article.resourcesn.md" Seite der Web-Ausgabe verweist. Zusammenfassend: Buch: enthält QR Code der auf Web verweist, Web enthält gerenderte Links.

Bei der Artikelerstellung können Resourcen natürlich auch einfach im letzten Sub-Kapitel im eigentlichen Artikel erstellt werden.

**Comment by bruderol** [comment]
und warum nicht den ganzen Artikel verlinken mit QR-code - dann finde ich dort auch alle Links - finde die Separierung in zwei Files reichlich übertrieben.

Würde aber vorschlagen dass wir vorgeben, wo die weiterführenden Links im Artikel typischerweise zu positionieren sind im Beispiel Artikel.

**Comment by abeggchr** [comment]
Den ganzen Artikel verlinken macht Sinn, sofern Resources vorhanden sind. 

Die Separierung in zwei Files ist zwingend, sonst muss es für das gedruckte Format manuell wieder auseinanderdividiert werden.

**Comment by abeggchr** [comment]
Described in "advanced contribution topics"
