### ISSUE TITLE
Article: Example first article

### ISSUE THREAD

**Issue by bruderol** [Zuehlke/fifty-shades#8]
Just a dummy first example article, for we have some test data.

**Comment by bruderol** [comment]
I think there should be a general structure for the articles, that make them a little bit more interesting to read. An introduction or abstract, the major part, a summary in the end and some links for further information to the topic (additional blog readings, webpages, etc.).

**Comment by abeggchr** [comment]
I'd leave the form (abstract, major part, summary) open to the authors.
Regarding further information I added issue #18.

@bruderol please close this issue if you agree

**Comment by bruderol** [comment]
I think we should at least ask every author to write a short abstract in the beginning. But it is okay for me to leave the rest of the form of the article up to the author and just recommend them to put some links to additional resources at the end of the article.

**Comment by abeggchr** [comment]
Do not agree with @bruderol: I do not think a summary is required in the beginning of a 10min read. I consider it a good writing practice to start with a problem situation and then dive into the solution. This attracts a reader and if she doesn't agree on the problem, she will skip the article.

Either way, I would really leave the form open to the authors.

**Comment by bruderol** [comment]
summary, was not what I meant with abstract.
I agree with what @abeggchr said.
What I meant with abstract: a first short paragraph that explains what the article is about. Why should I read the article? What problem does it solve? Or why could it be interesting for me?
Abstract was the wrong word for what I meant probably. 
Teaser or Problem situation is exactly what I meant. Just coming in 2-3 sentences to the point, what the articel is about and why it could/should interest me.

**Comment by bruderol** [comment]
I introduced a new label, such that we can see the "admin"-backlog much faster: https://github.com/Zuehlke/zuehlke-book/labels/admin

**Comment by abeggchr** [comment]
done
